
# True color support for Ghostty
set -g default-terminal "tmux-256color"

set -g prefix C-s
unbind C-b
bind C-s send-prefix

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

unbind %
bind v  split-window -h -c "#{pane_current_path}"

unbind '"'
bind s split-window -v -c "#{pane_current_path}"

set -g mouse on

set-window-option -g mode-keys vi

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'colour6'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
